services:
  mysql:
    image: mysql:8.0
    container_name: retail-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_DATABASE: retaildb
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password